[package]
name = "job-shop-ea"
version = "0.1.0"
edition = "2021"
authors = ["vilaureu"]
description = "Job-shop scheduling solver using an evolutionary algorithm."

[dependencies]
structopt = { version = "0.3", default-features = false, features = ["color"] }
